Script SQL

create database datawarehouse;

use datawarehouse;

create table fato_vendas (
   CodigoVenda smallint,
   DataVenda date,
   CodigoCliente smallint,
   CodigoProduto smallint,
   Quantidade int,
   ValorUnitario decimal(18,2),
   CodigoVendedor smallint,
   CodigoCanalVendas smallint,
   CodigoStatus smallint,
   Deletado smallint
);

-- Inserindo dados (1)
insert into fato_vendas values (1,'2010-02-01 00:00:00',1,1,4000,0.34,2,1,1,0);

insert into fato_vendas values (2,'2010-02-01 00:00:00',1,null,4000,0.34,2,1,1,0);

-- Inserindo dados (*)
insert into fato_vendas values (3,'2010-02-01 00:00:00',5,1,4200,0.34,4,1,1,0),
(4,'2010-02-02 00:00:00',3,2,250,7.00,2,1,1,0),
(5,'2010-02-03 00:00:00',4,1,4500,0.34,1,1,1,0),
(7,'2010-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(8,'2010-03-06 00:00:00',7,1,12000,0.34,2,1,1,0),
(9,'2010-04-07 00:00:00',8,1,17500,0.34,3,1,1,0),
(11,'2011-12-08 00:00:00',2,1,7000,0.34,9,1,1,0),
(12,'2012-12-08 00:00:00',2,1,8000,0.34,9,1,1,0),
(13,'2013-12-08 00:00:00',2,1,8000,0.34,9,1,1,0),
(14,'2014-12-08 00:00:00',2,1,9000,0.34,9,1,1,0),
(15,'2015-12-08 00:00:00',2,1,9000,0.34,9,1,1,0),
(16,'2016-12-08 00:00:00',2,1,10000,0.34,9,1,1,0),
(17,'2017-12-08 00:00:00',2,1,10000,0.34,9,1,1,0),
(18,'2018-12-08 00:00:00',2,1,11000,0.34,9,1,1,0),
(19,'2019-12-08 00:00:00',2,1,11000,0.34,9,1,1,0),
(20,'2020-12-08 00:00:00',2,1,12000,0.34,9,1,1,0),
(21,'2021-01-09 00:00:00',2,1,5000,0.34,9,2,1,0 ),
(22,'2021-03-07 00:00:00',2,1,5000,0.34,9,2,1,0 ),
(23,'2021-08-07 00:00:00',2,1,20000,0.34,9,2,2,1),
(24,'2021-08-08 00:00:00',2,1,25000,0.34,9,1,3,0),
(25,'2010-04-07 00:00:00',8,1,9000,0.34,3,1,1,0 ),
(26,'2011-04-07 00:00:00',8,1,9500,0.34,3,1,1,0 ),
(27,'2012-04-07 00:00:00',8,1,9500,0.34,3,1,1,0 ),
(28,'2013-04-07 00:00:00',8,1,9500,0.34,3,1,1,0 ),
(29,'2014-04-07 00:00:00',8,1,9500,0.34,3,1,1,0 ),
(30,'2014-04-07 00:00:00',8,1,9500,0.34,3,1,1,0 ),
(31,'2015-04-07 00:00:00',8,1,10500,0.34,3,1,1,0),
(32,'2016-04-07 00:00:00',8,1,11500,0.34,3,1,1,0),
(33,'2017-04-07 00:00:00',8,1,12500,0.34,3,1,1,0),
(34,'2018-04-07 00:00:00',8,1,13500,0.34,3,1,1,0),
(35,'2019-04-07 00:00:00',8,1,14500,0.34,3,1,1,0),
(36,'2020-04-07 00:00:00',8,1,15500,0.34,3,1,1,0),
(37,'2021-04-07 00:00:00',8,1,17500,0.34,3,2,1,0),
(38,'2021-04-07 00:00:00',2,1,10000,0.34,9,2,1,0),
(39,'2011-02-01 00:00:00',1,1,4000,0.34,2,1,1,0 ),
(40,'2012-02-01 00:00:00',1,1,14000,0.34,2,1,2,0),
(41,'2013-02-01 00:00:00',1,1,24000,0.34,2,1,1,0),
(42,'2014-02-01 00:00:00',1,1,34000,0.34,2,1,1,0),
(43,'2015-02-01 00:00:00',1,1,44000,0.34,2,1,1,0),
(45,'2017-02-01 00:00:00',1,1,4000,0.34,2,1,1,0 ),
(46,'2018-02-01 00:00:00',1,1,4000,0.34,2,1,1,0 ),
(47,'2019-02-01 00:00:00',1,1,4000,0.34,2,1,1,0 ),
(48,'2020-02-01 00:00:00',1,1,4000,0.34,2,1,1,0 ),
(49,'2021-02-01 00:00:00',1,1,14000,0.34,2,2,1,0),
(50,'2011-02-01 00:00:00',5,1,4200,0.34,4,1,1,0 ),
(51,'2012-02-01 00:00:00',5,1,4200,0.34,4,1,1,0 ),
(52,'2013-02-01 00:00:00',5,1,4200,0.34,4,1,1,0 ),
(53,'2014-02-01 00:00:00',5,1,14200,0.34,4,1,1,0),
(54,'2015-02-01 00:00:00',5,1,14200,0.34,4,1,1,0),
(55,'2016-02-01 00:00:00',5,1,24200,0.34,4,1,2,1),
(56,'2017-02-01 00:00:00',5,1,24200,0.34,4,1,1,0),
(57,'2018-02-01 00:00:00',5,1,24200,0.34,4,1,1,0),
(58,'2019-02-01 00:00:00',5,1,24200,0.34,4,1,1,0),
(59,'2020-02-01 00:00:00',5,1,4200,0.34,4,1,1,0 ),
(60,'2021-08-07 00:00:00',5,1,4200,0.34,4,2,1,0 ),
(61,'2011-02-01 00:00:00',4,1,4500,0.34,1,1,1,0 ),
(62,'2012-02-03 00:00:00',4,1,4500,0.34,1,1,1,0 ),
(63,'2013-02-02 00:00:00',4,1,14500,0.34,1,1,1,0),
(64,'2014-02-03 00:00:00',4,1,14500,0.34,1,1,1,0),
(65,'2015-02-03 00:00:00',4,1,14500,0.34,1,1,1,0),
(66,'2016-02-03 00:00:00',4,1,14500,0.34,1,1,1,0),
(67,'2017-04-04 00:00:00',4,1,14500,0.34,1,1,2,1),
(68,'2018-05-05 00:00:00',4,1,14500,0.34,1,1,1,0),
(69,'2019-06-07 00:00:00',4,1,14500,0.34,1,1,1,0),
(70,'2020-07-07 00:00:00',4,1,14500,0.34,1,1,1,0),
(71,'2021-08-07 00:00:00',4,1,14500,0.34,1,2,1,0),
(72,'2011-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(73,'2013-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(74,'2015-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(75,'2017-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(76,'2018-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(77,'2019-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(78,'2020-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(79,'2021-03-05 00:00:00',6,1,12500,0.34,2,1,1,0),
(80,'2021-04-05 00:00:00',6,1,12500,0.34,2,2,1,0),
(81,'2021-08-07 00:00:00',6,1,12500,0.34,2,2,1,0),
(82,'2012-03-06 00:00:00',7,1,12000,0.34,2,1,1,0),
(83,'2014-03-06 00:00:00',7,1,12000,0.34,2,1,3,0),
(84,'2016-03-06 00:00:00',7,1,12000,0.34,2,1,1,0),
(85,'2019-03-06 00:00:00',7,1,12000,0.34,2,1,1,0),
(86,'2020-03-06 00:00:00',7,1,22000,0.34,2,1,1,0),
(87,'2021-03-06 00:00:00',7,1,22000,0.34,2,2,1,0),
(88,'2021-06-06 00:00:00',7,1,42000,0.34,2,2,1,0),
(89,'2021-08-07 00:00:00',7,1,52000,0.34,2,2,1,0),
(90,'2011-02-02 00:00:00',3,2,11250,7.00,2,1,1,0),
(91,'2012-02-02 00:00:00',3,2,12250,7.00,2,1,1,0),
(92,'2013-02-02 00:00:00',3,2,13250,7.00,2,1,1,0),
(93,'2014-02-02 00:00:00',3,2,14250,7.00,2,1,1,0),
(94,'2015-02-02 00:00:00',3,2,15250,7.00,2,1,1,0),
(95,'2016-02-02 00:00:00',3,2,16250,7.00,2,1,1,0),
(96,'2017-02-02 00:00:00',3,2,17250,7.00,2,1,1,0),
(97,'2018-02-02 00:00:00',3,2,18250,7.00,2,1,1,0),
(98,'2019-02-02 00:00:00',3,2,19250,7.00,2,1,1,0),
(99,'2020-03-02 00:00:00',3,2,19250,7.00,2,1,1,0),
(100,'2021-07-02 00:00:00',3,2,19250,7.00,2,1,1,0),
(101,'2015-02-02 00:00:00',10,2,15250,7.00,10,1,3,0),
(102,'2016-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(103,'2017-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(104,'2018-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(105,'2019-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(106,'2020-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(107,'2021-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(108,'2021-07-01 00:00:00',10,2,15250,7.00,10,2,1,0),
(110,'2015-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(112,'2016-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(114,'2017-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(115,'2018-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(116,'2018-03-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(117,'2020-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(118,'2021-05-15 00:00:00',9,2,25250,7.00,8,1,1,0),
(120,'2010-02-13 00:00:00',11,1,4500,0.34,6,1,1,0),
(121,'2011-02-03 00:00:00',11,1,4500,0.34,6,1,1,0),
(122,'2012-02-03 00:00:00',11,1,4500,0.34,6,1,1,0),
(123,'2013-01-03 00:00:00',11,1,4500,0.34,6,1,1,0),
(124,'2014-02-03 00:00:00',11,1,4500,0.34,6,1,1,0),
(125,'2015-02-03 00:00:00',11,1,4500,0.34,6,1,3,0),
(126,'2016-02-03 00:00:00',11,1,4500,0.34,6,1,1,0),
(127,'2017-06-03 00:00:00',11,1,14500,0.34,6,1,1,0),
(128,'2018-08-03 00:00:00',11,1,14500,0.34,6,1,1,0),
(129,'2019-05-03 00:00:00',11,1,14500,0.34,6,1,1,0),
(130,'2020-01-03 00:00:00',11,1,34500,0.34,6,1,1,0),
(131,'2021-08-04 00:00:00',11,1,44500,0.34,6,2,1,0),
(140,'2011-09-06 00:00:00',13,1,4500,0.34,7,1,1,0 ),
(141,'2012-09-06 00:00:00',13,1,4500,0.34,7,1,1,0 ),
(142,'2013-09-06 00:00:00',13,1,4500,0.34,7,1,1,0 ),
(143,'2014-09-06 00:00:00',13,1,4500,0.34,7,1,1,0 ),
(144,'2015-09-06 00:00:00',13,1,4500,0.34,7,1,1,0 ),
(145,'2016-09-06 00:00:00',13,1,14500,0.34,7,1,1,0),
(146,'2018-09-06 00:00:00',13,1,34500,0.34,7,1,1,0),
(147,'2019-09-06 00:00:00',13,1,44500,0.34,7,1,1,0),
(148,'2020-09-06 00:00:00',13,1,44500,0.34,7,1,1,0),
(149,'2021-05-15 00:00:00',13,1,44500,0.34,7,1,1,0),
(150,'2010-03-01 00:00:00',14,3,730,2.00,5,1,1,0  ),
(151,'2011-03-05 00:00:00',14,3,1730,2.00,5,1,1,0 ),
(152,'2012-05-01 00:00:00',14,3,2730,2.00,5,1,1,0 ),
(153,'2013-04-03 00:00:00',14,3,3730,2.00,5,1,1,0 ),
(154,'2014-07-01 00:00:00',14,3,4730,2.00,5,1,1,0 ),
(155,'2015-06-02 00:00:00',14,3,5730,2.00,5,1,1,0 ),
(156,'2016-07-29 00:00:00',14,3,7730,2.00,5,1,1,0 ),
(157,'2017-03-23 00:00:00',14,3,19730,2.00,5,1,1,0),
(158,'2019-02-17 00:00:00',14,3,19730,2.00,5,1,1,0),
(159,'2020-02-14 00:00:00',14,3,19730,2.00,5,1,1,0),
(160,'2021-07-02 00:00:00',14,3,19730,2.00,5,2,1,0),
(170,'2010-05-21 00:00:00',18,5,10030,9.00,2,1,1,0),
(171,'2012-12-21 00:00:00',18,5,10030,9.00,2,1,1,0),
(172,'2014-02-01 00:00:00',18,5,10030,9.00,2,1,1,0),
(173,'2016-07-05 00:00:00',18,5,10030,9.00,2,1,1,0),
(174,'2017-08-11 00:00:00',18,5,10030,9.00,2,1,1,0),
(175,'2018-06-25 00:00:00',18,5,10030,9.00,2,1,1,0),
(176,'2019-05-28 00:00:00',18,5,20030,9.00,2,1,1,0),
(177,'2020-03-30 00:00:00',18,5,20030,9.00,2,1,1,0),
(178,'2021-04-01 00:00:00',18,5,20030,9.00,2,1,1,0),
(180,'2010-03-15 00:00:00',16,4,750,0.50,1,1,1,0  ),
(181,'2012-04-30 00:00:00',16,4,1750,0.50,1,1,1,0 ),
(182,'2013-12-25 00:00:00',16,4,2750,0.50,1,1,3,0 ),
(183,'2014-11-21 00:00:00',16,4,3750,0.50,1,1,1,0 ),
(184,'2015-03-16 00:00:00',16,4,4750,0.50,1,1,1,0 ),
(185,'2017-03-11 00:00:00',16,4,6750,0.50,1,1,1,0 ),
(186,'2018-06-05 00:00:00',16,4,5750,0.50,1,1,1,0 ),
(187,'2019-05-04 00:00:00',16,4,18750,0.50,1,1,1,0),
(188,'2020-07-02 00:00:00',16,4,19750,0.50,1,1,1,0),
(189,'2021-08-01 00:00:00',16,4,20750,0.50,1,1,1,0),
(190,'2021-08-03 00:00:00',16,4,20750,0.50,1,2,1,0),
(191,'2021-08-05 00:00:00',16,4,20750,0.50,1,2,1,0),
(192,'2021-08-07 00:00:00',16,4,30750,0.50,1,2,1,0),
(200,'2021-03-15 00:00:00',17,6,1750,0.25,5,2,1,0 ),
(201,'2021-04-05 00:00:00',17,6,11750,0.25,5,2,1,0),
(202,'2021-05-15 00:00:00',17,6,21750,0.25,5,2,1,0),
(203,'2021-05-16 00:00:00',17,6,31750,0.25,5,2,1,0),
(204,'2021-07-01 00:00:00',17,6,41750,0.25,5,2,1,0),
(205,'2021-07-15 00:00:00',17,6,51750,0.25,5,2,1,0),
(206,'2021-08-01 00:00:00',17,6,71750,0.25,5,2,1,0),
(207,'2021-08-07 00:00:00',17,6,91750,0.25,5,2,3,0);

insert into fato_vendas values 
(208,'2022-01-15 00:00:00',10,5,10030,9.00,8,1,1,0),
(209,'2022-01-28 00:00:00',10,5,10030,9.00,8,1,1,0),
(210,'2022-02-20 00:00:00',14,5,10030,9.00,8,2,1,0),
(211,'2022-03-03 00:00:00',14,5,10030,9.00,9,2,1,0),
(212,'2022-03-15 00:00:00',17,6,1750,0.25,5,2,1,0 ),
(213,'2022-04-15 00:00:00',17,4,11750,0.50,5,2,1,0),
(214,'2022-05-25 00:00:00',17,4,21750,0.50,5,2,1,0),
(215,'2022-05-31 00:00:00',17,4,31750,0.50,5,2,1,0),
(216,'2022-06-20 00:00:00',17,6,41750,0.25,5,2,1,0),
(217,'2022-07-07 00:00:00',17,6,51750,0.25,5,2,1,0),
(218,'2022-08-29 00:00:00',14,6,71750,0.25,5,2,1,0),
(219,'2022-09-15 00:00:00',14,6,91750,0.25,5,2,3,0),
(220,'2022-08-20 00:00:00',6,6,41750,0.25,5,2,1,0),
(221,'2022-08-15 00:00:00',6,6,51750,0.25,5,2,1,0),
(222,'2022-08-21 00:00:00',6,6,71750,0.25,5,2,1,0),
(223,'2022-08-23 00:00:00',6,6,91750,0.25,5,2,3,0),
(224,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,3,0),
(225,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(226,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(227,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(228,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(229,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(230,'2022-02-02 00:00:00',10,2,15250,7.00,10,1,1,0),
(231,'2022-07-01 00:00:00',10,2,15250,7.00,10,2,1,0),
(232,'2022-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(233,'2022-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(234,'2022-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(235,'2022-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(236,'2022-03-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(237,'2022-02-02 00:00:00',9,2,25250,7.00,8,1,1,0),
(238,'2022-05-15 00:00:00',9,2,25250,7.00,8,1,1,0),
(239,'2020-05-21 00:00:00',18,5,10030,9.00,2,1,1,0),
(240,'2020-12-21 00:00:00',18,5,10030,9.00,2,1,1,0),
(241,'2020-02-01 00:00:00',18,5,10030,9.00,2,1,1,0),
(242,'2020-07-05 00:00:00',18,5,10030,9.00,2,1,1,0),
(243,'2020-08-11 00:00:00',18,5,10030,9.00,2,1,1,0),
(244,'2020-06-25 00:00:00',18,5,10030,9.00,2,1,1,0),
(245,'2020-05-28 00:00:00',18,5,20030,9.00,2,1,1,0),
(246,'2020-03-30 00:00:00',18,5,20030,9.00,2,1,1,0),
(247,'2020-04-01 00:00:00',18,5,20030,9.00,2,1,1,0),
(248,'2023-02-01 00:00:00',18,5,20030,9.00,2,1,1,0),
(249,'2023-03-01 00:00:00',18,5,20030,9.00,2,1,1,0),
(250,'2023-04-01 00:00:00',18,5,30030,9.00,2,1,1,0),
(251,'2023-04-07 00:00:00',18,5,10030,9.00,2,1,1,0);

create table dim_produto (
   CodigoProduto smallint,
   NomeProduto varchar(50),
   TipoProduto varchar(1),
   UnidadeProduto varchar(2),
   SaldoProduto int,
   StatusProduto varchar(50));



insert into dim_produto values (1,'Produto A','A','KG',20000,'Ativo'),
(2,'Produto C' ,'A','KG',5000,  'Ativo'),
(3,'Produto E' ,'B','KG',2000,  'Ativo'),
(5,'Produto CH','A','KG',2000,  'Ativo'),
(4,'Produto SL','A','KG',30000, 'Ativo'),
(6,'Produto TN','C','KG',1000,  'MVP - validação');


insert into dim_produto values (8,'Produto AA','A','KG',20000,'Ativo');
insert into dim_produto values (9,null,'A','KG',20000,'Inativo');

create table dim_cliente (
   CodigoCliente int,
   NomeCliente varchar(50),
   Idade smallint,
   Classificacao smallint,
   Sexo varchar(1),
   Cidade varchar(50),
   Estado varchar(50),
   Pais varchar(50));


insert into dim_cliente values 
(1,'Cliente AA',30,3,'M','Florianópolis','Santa Catarina','Brasil'),
(5,'Cliente BB',20,2,'F','Belo Horizonte','Minas Gerais','Brasil'),
(3,'Cliente BC',25,4,'M','Baturité','Ceará','Brasil'),
(4,'Cliente CC',19,2,'F','Fortaleza','Ceará','Brasil'),
(6,'Cliente DD',19,2,'F','Goiânia','Goiás','Brasil'),
(7,'Cliente DE',39,5,'F','João Pessoa','Paraíba','Brasil'),
(8,'Cliente EE',26,4,'M','Natal','Rio Grande do Norte','Brasil'),
(2,'Cliente EF',31,3,'M','Belo Horizonte','Minas Gerais','Brasil'),
(10,'Cliente ABC',50,1,'M','São Paulo','São Paulo','Brasil'),
(9,'Cliente BCA',25,4,'F','Rio de Janeiro','Rio de Janeiro','Brasil'),
(11,'Cliente CCC',18,2,'F','Salvador','Bahia','Brasil'),
(13,'Cliente MAC',37,5,'F','Maceió','Alagoas','Brasil'),
(14,'Cliente MGS',50,1,'F','Campo Grande','Mato Grosso do Sul','Brasil'),
(18,'Cliente GRM',55,1,'M','Gramado','Rio Grande do Sul','Brasil'),
(16,'Cliente PIR',32,3,'M','Piripiri','Piauí','Brasil'),
(17,'Cliente MTG',38,5,'F','Palmas','Tocantins','Brasil');